echo '!.gitignore' > bin/.gitignore
echo '!.gitignore' > doc/.gitignore
echo '!.gitignore' > lib/.gitignore
echo '!.gitignore' > inc/.gitignore
echo '!.gitignore' > src/.gitignore
echo '!.gitignore' > tmp/.gitignore
echo '!.gitignore' > app/.gitignore
echo '!.gitignore' > hw/.gitignore
echo '!.gitignore' > arch/.gitignore
echo '!.gitignore' > cpu/.gitignore
